// <auto-generated>
// Rewired Constants
// This list was generated on 11/13/2018 4:00:50 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

public static partial class RewiredActions {
    // Default
    // Gameplay
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Horizontal Movement")]
    public const int Movement_Horizontal = 25;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Vertical Movement")]
    public const int Movement_Vertical = 26;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Jump")]
    public const int Jump = 41;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Dash")]
    public const int Dash = 27;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Slide")]
    public const int Slide = 53;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Fire")]
    public const int Fire = 29;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Aim Mode")]
    public const int Aim_Mode = 33;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Gamepad Horizontal Aim Axis")]
    public const int Aim_Horizontal = 32;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Gamepad Vertical Aim Axis")]
    public const int Aim_Vertical = 34;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Reload")]
    public const int Reload = 30;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Switch Weapon")]
    public const int Switch_Weapon = 31;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Interact")]
    public const int Interact = 35;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Walk")]
    public const int Walk = 44;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game Controls", friendlyName = "Pause")]
    public const int Pause = 36;
    // Menu
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "Horizontal Menu Movement")]
    public const int UIHorizontal = 37;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "Vertical Menu Movement")]
    public const int UIVertical = 38;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "Menu Submit")]
    public const int UISubmit = 39;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "Menu Cancel")]
    public const int UICancel = 40;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "Mouse X Axis")]
    public const int Mouse_Horizontal = 42;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "Mouse Y Axis")]
    public const int Mouse_Vertical = 43;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "Previous Tab")]
    public const int PrevTab = 46;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "Next Tab")]
    public const int NextTab = 47;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "Zoom")]
    public const int Zoom = 49;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "View Level")]
    public const int ViewLevel = 51;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "MenuStart")]
    public const int MenuStart = 48;
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu Controls", friendlyName = "Change Xbox Profile")]
    public const int ChangeProfile = 52;
}
public static partial class Layout {
    public static partial class Joystick {
        public const int Default = 0;
    }
    public static partial class Keyboard {
        public const int Default = 0;
    }
    public static partial class Mouse {
        public const int Default = 0;
    }
    public static partial class CustomController {
        public const int Default = 0;
    }
}
